services:
  redis:
    image: redis:7-alpine
    container_name: texfolio-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis-data:/data

  latex-renderer:
    build:
      context: ./apps/latex-renderer
    container_name: texfolio-latex
    volumes:
      # Mount the temp directory so we can read .tex and write .pdf
      - ./apps/api/temp:/app/temp
    working_dir: /app/temp
    restart: unless-stopped

volumes:
  redis-data:
